TaskBoard.AP/Controllers/SprintsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TaskBoard.API.Contracts.Sprint;
using TaskBoard.Domain.Interfaces.Services;
using TaskBoard.Domain.Models;

namespace TaskBoard.API.Controllers
{
    public class SprintsController : Controller
    {

        private readonly ISprintsService _sprintsService;
        private readonly IUsersService _usersService;
        public SprintsController(ISprintsService sprintsService, IUsersService usersService)
        {
            _sprintsService = sprintsService;
            _usersService = usersService;   
        }

        [HttpGet]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public IActionResult CreateSprint(Guid idProject)
        {
            var sprintRequest = new CreateSprintRequest(
                idProject, 
                string.Empty, 
                string.Empty, 
                DateTime.Now ,
                string.Empty);

            return View(sprintRequest);
        }

        [HttpPost]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public async Task<IActionResult> CreateSprint(CreateSprintRequest sprintRequest)
        {
            var sprint = SprintModel.Create(
                sprintRequest.ProjectId, 
                Guid.Empty, 
                sprintRequest.Title, 
                sprintRequest.Description, 
                sprintRequest.DateEnd, 
                sprintRequest.Comment, 
                Guid.Empty);

            if (sprint.IsFailure)
            {
                return View(sprint);
            }

            await _sprintsService.CreateSprint(sprint.Value);

            return RedirectToAction("GetProject", "Projects", new { id = sprintRequest.ProjectId });
        }

        [HttpGet]
        [Authorize(Policy = "AllNotBanedUsers")]
        public async Task<IActionResult> GetSprint(Guid id)
        {

            var sprint = await _sprintsService.GetSprint(id);

            if (sprint.IsSuccess)
            {
                return View(sprint.Value);
            }

            return View(sprint.Error);
        }

        [HttpGet]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public async Task<IActionResult> DeleteSprint(Guid id)
        {
            var sprint = await _sprintsService.GetSprint(id);

            await _sprintsService.DeleteSprint(id);

            return RedirectToAction("GetProject", "Projects", new {id = sprint.Value.ProjectId});
        }

        [HttpGet]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public async Task<IActionResult> EditSprint(Guid id)
        {
            var sprint = await _sprintsService.GetSprint(id);
            if (sprint.IsSuccess)
            {
                var sprintRequest = new UpdateSprintRequest(
                    id,
                    sprint.Value.ProjectId,
                    sprint.Value.Title,
                    sprint.Value.Description,
                    sprint.Value.DateEnd,
                    sprint.Value.Comment);

                return View(sprintRequest);
            }

            return RedirectToAction("GetProject", "Projects",  new { id = sprint.Value.ProjectId});
        }

        [HttpPost]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public async Task<IActionResult> EditSprint(UpdateSprintRequest sprintRequest)
        {
            var sprint = SprintModel.Create(
                sprintRequest.ProjectId,
                sprintRequest.Id,
                sprintRequest.Title,
                sprintRequest.Description,
                sprintRequest.DateEnd,
                sprintRequest.Comment,
                Guid.Empty);

            if (sprint.IsFailure)
            {
                return View(sprintRequest);
            }

            var sprintUpdate = await _sprintsService.UpdateSprint(sprint.Value);

            if (sprintUpdate.IsSuccess)
            {
                return RedirectToAction("GetSprint", new { id = sprintRequest.Id });
            }

            return View(sprintRequest);
        }

        [HttpGet]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public IActionResult SetUser(Guid id)
        {
            ViewData["SprintId"] = id;
            return View("SetUser");
        }

        [HttpPost]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public async Task<IActionResult> SetUser(Guid id, string email)
        {

            var user = await _usersService.GetUserByEmail(email);

            if (user.IsFailure)
            {
                ViewData["Message"] = $"{user.Error}";
                ViewData["SprintId"] = id;
                return View("SetUser");
            }

            await _sprintsService.SetUser(id, user.Value);

            return RedirectToAction("GetSprint", new { id });
        }

        [HttpGet]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public async Task<IActionResult> RemoveUser(Guid id)
        {

            await _sprintsService.RemoveUser(id);

            return RedirectToAction("GetSprint", new { id });
        }
    }
}

TaskBoard.AP/Controllers/UsersController.cs
using Azure.Core;
using CSharpFunctionalExtensions;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TaskBoard.API.Contracts.User;
using TaskBoard.Domain.Interfaces.Services;
using TaskBoard.Domain.Models;

namespace TaskBoard.API.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUsersService _usersService;
        public UsersController(IUsersService usersService)
        {
            _usersService = usersService;
        }
        [HttpGet]
        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> GetAll()
        {
            var users = await _usersService.GetAll();

            if (users.IsSuccess)
            {
                return View(users.Value);
            }

            return View(users.Error);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> GetUser(Guid id)
        {
            var user = await _usersService.GetUserById(id);

            if (user.IsSuccess)
            {
                return View(user.Value);
            }

            return View(user.Error);
        }


        [HttpGet]
        [Authorize(Roles = "Администратор")]
        public IActionResult CreateUser()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Администратор")]
        public IActionResult CreateUser(CreateUserRequest userRequest)
        {
            if (!ModelState.IsValid)
            {
                return View(userRequest);
            }

            var user = UserModel.Create(
                Guid.Empty,
                userRequest.Name,
                userRequest.Password,
                userRequest.Email);


            if (user.IsFailure)
            {
                return BadRequest(user.Error);
            }

            user.Value.UpdateRole(userRequest.Role);

            _usersService.CreateUser(user.Value);
            return RedirectToAction("GetAll");
        }

        [HttpGet]
        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> UpdateRole(Guid id)
        {
            var user = await _usersService.GetUserById(id);

            if (user.IsSuccess)
            {
                var userRequest = new UpdateUserRequest(
                    user.Value.Id,
                    string.Empty,
                    string.Empty,
                    string.Empty,
                    string.Empty,
                    user.Value.Role);

                return View(userRequest);
            }
            return RedirectToAction("GetAll");

        }

        [HttpPost]
        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> UpdateRole(UpdateUserRequest userRequest)
        {
            
            var userUpdate = await _usersService.UpdateUserRole(userRequest.Id, userRequest.Role);

            if (userUpdate.IsSuccess)
            {
                return RedirectToAction("GetAll", userRequest.Id);
            }

            return View(userRequest);
        }


        [HttpGet]
        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> BanedUser(Guid id)
        {
            var user = await _usersService.GetUserById(id);

            if (user.Value.Email != "spacyworktesting@yandex.ru")
            {
                var banUser = new BanUserRequest(id, string.Empty);
                return View(banUser);
            }

            return BadRequest("Запрещенно");
        }

        [HttpPost]
        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> BanedUser(BanUserRequest request)
        {

            var userDelete = await _usersService.BanUser(request.Id, request.Cause);

            if (userDelete.IsSuccess)
            {
                var user = await _usersService.GetUserById(request.Id);

                var message = new IdentityMessage()
                {
                    Destination = user.Value.Email,
                    Subject = "Сообщение о блокировке",
                    Body = $"Ваш аккаунт в сервисе 'TaskBoard' был заблокирован по причине: {request.Cause}"
                };
                EmailService emailService = new EmailService();
                await emailService.SendAsync(message);
                return View("GetAll");
            }

            return BadRequest("Пользователь не найден");


        }

        [HttpGet]
        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> UnBanedUser(Guid id)
        {

            var userDelete = await _usersService.UnbanUser(id);

            if (userDelete.IsSuccess)
            {
                var user = await _usersService.GetUserById(id);

                var message = new IdentityMessage()
                {
                    Destination = user.Value.Email,
                    Subject = "Сообщение о разблокировке",
                    Body = $"{user.Value.Name} Ваш аккаунт в сервисе 'TaskBoard' был разблокирован"
                };
                EmailService emailService = new EmailService();
                await emailService.SendAsync(message);

                return RedirectToAction("GetAll");
            }

            return BadRequest("Пользователь не найден");
        }

        [HttpGet]
        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> GetBlackList()
        {

            var blackList = await _usersService.GetBanUser();

            if (blackList.IsSuccess)
            {
                return View(blackList.Value);
            }

            return BadRequest($"{blackList.Error}");
        }

    }
}

TaskBoard.AP/Views/Users/BanedUser.cshtml
@using TaskBoard.API.Contracts;
@using TaskBoard.Domain.Extensions;
@using TaskBoard.Domain.Models;
@using TaskBoard.Domain.Enum;
@using TaskBoard.API.Contracts.User;
@model BanUserRequest

<h2>Создание пользователя</h2>
<form asp-action="BanedUser" method="post">
    <input type="hidden" name="Id" value="@Model.Id">  
    <div class="form-group">
        <label for="Cause">Причина блокировки:</label>
        <input type="text" class="form-control" id="Cause" name="Cause" required>
    </div>
    <button type="submit" class="btn btn-primary">Заблокировать</button>
    <a href="@Url.Action("GetAll")" class="btn btn-secondary">Назад к списку пользователе</a>
</form>

TaskBoard.AP/Views/Users/CreateUser.cshtml
@using TaskBoard.API.Contracts
@using TaskBoard.Domain.Models;
@using TaskBoard.Domain.Enum;
@using TaskBoard.Domain.Extensions;
@using TaskBoard.API.Contracts.User;
@model CreateUserRequest

<h2>Создание пользователя</h2>
<form asp-action="CreateUser" method="post">
    <div class="form-group">
        <label for="Name">Имя:</label>
        <input type="text" class="form-control" id="Name" name="Name" required>
    </div>
    <div class="form-group">
        <label for="Password">Пароль:</label>
        <input type="password" class="form-control" id="Password" name="Password" required>
    </div>
    <div class="form-group">
        <label for="Email">Email:</label>
        <input type="email" class="form-control" id="Email" name="Email" required>
    </div>
    <div class="form-group">
        <label for="Role">Роль:</label>
        <select asp-for="Role" asp-items="Html.GetEnumSelectList<UserRole>().Where(x => x.Value != nameof(UserRole.Ban))">@Model.Role.GetDisplayName()</select>
    </div>
    <button type="submit" class="btn btn-primary">Создать</button>
    <a href="@Url.Action("GetAll")" class="btn btn-secondary">Назад к списку</a>
</form>

TaskBoard.AP/Views/Users/GetAll.cshtml
@using TaskBoard.Domain.Models;
@using TaskBoard.Domain.Enum;
@using TaskBoard.Domain.Extensions;
@model List<UserModel>

<h2>Список пользователей: </h2>
<a href="@Url.Action("CreateUser", "Users")" class="btn btn-success">Создать пользователя</a>
<a href="@Url.Action("GetBlackList", "Users")" class="btn btn-dark">Черный список</a>
<table class="table">
    <thead>
        <tr>
            <th>Имя</th>
            <th>Email</th>
            <th>Роль</th>
            <th>Действие</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Name</td>
                <td>@user.Email</td>
                <td>@user.Role.GetDisplayName()</td>
                <td>
                    @if (user.Role != UserRole.Ban)
                    {
                        <a href="@Url.Action("UpdateRole","Users", new { id = user.Id })" class="btn btn-primary">Обновить роль</a>
                        <form asp-action="BanedUser" method="get" style="display:inline;">
                            <input type="hidden" name="id" value="@user.Id" />
                            <button type="submit" class="btn btn-danger">Забанить пользователя</button>
                        </form>
                    }
                    else
                    {
                        <form asp-action="UnBanedUser" method="get" style="display:inline;">
                            <input type="hidden" name="id" value="@user.Id" />
                            <button type="submit" class="btn btn-danger">Разбанить пользователя</button>
                        </form>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

TaskBoard.AP/Views/Users/GetBlackList.cshtml
@using TaskBoard.Domain.Models;
@using TaskBoard.Domain.Extensions;
@model List<BanModel>

<table class="table">
    <thead>
        <tr>
            <th>Имя</th>
            <th>Email</th>
            <th>Дата блокировки</th>
            <th>Причина блокировки</th>
            <th>Действие</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var banUser in Model)
        {
            <tr>
                <td>@banUser.User.Name</td>
                <td>@banUser.User.Email</td>
                <td>@banUser.DateBan</td>
                <td>@banUser.Сause</td>
                <td>
                    <a href="@Url.Action("UnBanedUser","Users", new { id = banUser.UserId })" class="btn btn-primary">Снять блокировку</a>
                </td>
            </tr>
        }
    </tbody>
</table>

TaskBoard.AP/Views/Users/GetUser.cshtml
@using TaskBoard.Domain.Extensions;
@model UserModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>User Details</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <h2>User Details</h2>
        <div class="row">
            <div class="col-md-6">
                <dl class="row">
                    <dt class="col-sm-3">Name:</dt>
                    <dd class="col-sm-9">@Model.Name</dd>
                    <dt class="col-sm-3">Email:</dt>
                    <dd class="col-sm-9">@Model.Email</dd>
                    <dt class="col-sm-3">Роль:</dt>
                    <dd class="col-sm-9">@Model.Role.GetDisplayName()</dd>
                </dl>
            </div>
        </div>
     </div>
        <h3>Спринты:</h3>

            @if (Model.Sprints.Any())
            {
                @foreach (var sprint in Model.Sprints)
                {
                    <p><a href="@Url.Action("GetSprint", "Sprints", new { id = sprint.Id })">@sprint.Title</a></p>
                }
            }
            else
            {
                <p>У пользователя пока нет спринтов</p>
            }
</body>
</html>

TaskBoard.AP/Views/Users/UpdateRole.cshtml
@using TaskBoard.API.Contracts;
@using TaskBoard.Domain.Extensions;
@using TaskBoard.Domain.Models;
@using TaskBoard.Domain.Enum;
@using TaskBoard.API.Contracts.User;
@model UpdateUserRequest

<h2>Создание пользователя</h2>
<form asp-action="UpdateRole" method="post">
    <input type="hidden" name="Name" value="@Model.Name">
    <input type="hidden" name="Password" value="@Model.Password">
    <input type="hidden" name="Email" value="@Model.Email">    
    <div class="form-group">
        <label for="Role">Роль:</label>
        <select asp-for="Role" asp-items="Html.GetEnumSelectList<UserRole>().Where(x => x.Value != nameof(UserRole.Ban))">@Model.Role.GetDisplayName()</select>
    </div>
    <button type="submit" class="btn btn-primary">Обновить</button>
    <a href="@Url.Action("GetAll")" class="btn btn-secondary">Назад к списку пользователе</a>
</form>