TaskBoard.AP/Controllers/FilesController.cs
using Microsoft.AspNetCore.Mvc;
using TaskBoard.Domain.Interfaces.Services;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace TaskBoard.API.Controllers
{
    public class FilesController : Controller
    {
        private readonly string _staticFilesPath =
           Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "StaticFiles");

        private readonly IFilesService _filesService;
        private readonly ISprintsService _sprintService;
        private readonly ITasksService _tasksService;
        public FilesController(IFilesService filesService, ISprintsService sprintsService, ITasksService ITasksService)
        {
            _filesService = filesService;
            _sprintService = sprintsService;
            _tasksService = ITasksService;
        }

        [HttpPost]
        [Authorize(Roles = "Администратор, Менеджер")]
        public async Task<IActionResult> UploadFileToSprint(Guid sprintId, IFormFile file)
        {
            var path = Path.Combine(_staticFilesPath, "SprintFiles");
            var fileModel = await _filesService.CreateFile(file, path);

            if (fileModel.IsFailure)
            {
                return BadRequest(fileModel.Error);
            }

            await _filesService.AddFileToSprint(sprintId, fileModel.Value);

            return RedirectToAction("GetSprint", "Sprints", new { id = sprintId }); ;

        }

        [HttpPost]
        [Authorize(Policy = "AllNotBanedUsers")]
        public async Task<IActionResult> UploadFileToTaks(Guid taskId, IFormFile file)
        {
            var path = Path.Combine(_staticFilesPath, "TaskFiles");
            var fileModel = await _filesService.CreateFile(file, path);

            if (fileModel.IsFailure)
            {
                return BadRequest(fileModel.Error);
            }

            await _filesService.AddFileToTask(taskId, fileModel.Value);

            return RedirectToAction("GetTask", "Tasks", new { id = taskId }); ;

        }

        [HttpPost]
        [Authorize(Roles = "Администратор, Менеджер")]
        public async Task<IActionResult> DeleteFile(Guid id)
        {
                  
            var file = await _filesService.GetFile(id);

            var deletionResult  = await _filesService.DeleteFile(id);
            if (deletionResult.IsFailure)
            {
                return StatusCode(500, "Не удалось удалить файл.");
            }

            var sprint = await _sprintService.GetSprint(file.Value.OwnerId);
            if (sprint.IsSuccess)
            {
                var path = Path.Combine(_staticFilesPath, "SprintFiles", file.Value.FileName);
                System.IO.File.Delete(path);
                return RedirectToAction("GetSprint", "Sprints", new { id = file.Value.OwnerId });
            }

            var task = await _tasksService.GetTask(file.Value.OwnerId);
            if (task.IsSuccess)
            {
                var path = Path.Combine(_staticFilesPath, "TaskFiles", file.Value.FileName);
                System.IO.File.Delete(path);
                return RedirectToAction("GetTask", "Tasks", new { id = file.Value.OwnerId });
            }

            return RedirectToAction("GetSprint", "Sprints", new { id = file.Value.OwnerId }); 

        }

        [Authorize(Policy = "AllNotBanedUsers")]
        public async Task<IActionResult> DownloadFile(Guid id)
        {
            var file = await _filesService.GetFile(id);

            if (file.IsFailure)
            {
                return NotFound();
            }
            var path = Path.Combine(_staticFilesPath, "SprintFiles");

            var filePath = Path.Combine(path, file.Value.FileName);

            if (!System.IO.File.Exists(filePath))
            {
                path = Path.Combine(_staticFilesPath, "TaskFiles");

                filePath = Path.Combine(path, file.Value.FileName);
            }

            var fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read);
            var fileName = Path.GetFileName(file.Value.FileName);
            var contentType = "application/octet-stream"; 
            return File(fileStream, contentType, fileName);
        }
    }
}

TaskBoard.AP/Controllers/ProjectsController.cs
using CSharpFunctionalExtensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TaskBoard.API.Contracts.Project;
using TaskBoard.Domain.Interfaces.Services;
using TaskBoard.Domain.Models;
using TaskBoard.Service.Services;

namespace TaskBoard.API.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly IProjectsService _projectsService;
        private readonly IAuthorizationService _authorizationService;
        public ProjectsController(IProjectsService projectsService, IAuthorizationService authorizationService)
        {
            _projectsService = projectsService;
            _authorizationService = authorizationService;
        }

        [HttpGet]
        [Authorize(Policy = "AllNotBanedUsers")]
        public async Task<IActionResult> GetAll()
        {
            var projects = await _projectsService.GetProjects();

            if (projects.IsSuccess)
            {
                return View(projects.Value);
            }

            return View(projects.Error);
        }

        [HttpGet]
        [Authorize(Policy = "AllNotBanedUsers")]
        public async Task<IActionResult> GetProject(Guid id)
        {

            if (!_authorizationService.AuthorizeAsync(User, null, "AdminOrManagerPolicy").Result.Succeeded)
            {
                var userId = Guid.Parse(User.Claims.FirstOrDefault(c => c.Type == "userId").Value);

                var projectWithUserSprints = await _projectsService.GetProjectWithUserSprints(id, userId);

                if (projectWithUserSprints.IsFailure)
                {
                    return View(projectWithUserSprints.Error);
                }

                return View(projectWithUserSprints.Value);
            }
           
            var projectAllSprints = await _projectsService.GetProject(id);
            if (projectAllSprints.IsFailure)
            {
                return View(projectAllSprints.Error);
            }

            return View(projectAllSprints.Value);
        }

        [HttpGet]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public IActionResult CreateProject() 
        {
            return View();
        }

        [HttpPost]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public IActionResult CreateProject(CreateProjectRequest projectRequest)
        {
            if (!ModelState.IsValid)
            {
                return View(projectRequest);
            }

            var project = ProjectModel.Create(Guid.NewGuid(),projectRequest.Title, projectRequest.Description,new List<SprintModel>());

            if (project.IsFailure)
            {
                return BadRequest(project.Error);
            }
            _projectsService.CreateProject(project.Value);
            return RedirectToAction("GetAll");
        }

        [HttpGet]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public async Task<IActionResult> DeleteProject(Guid id) 
        { 
            await _projectsService.DeleteProject(id);

            return RedirectToAction("GetAll");
        }

        [HttpGet]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public async Task<IActionResult> EditProject(Guid id) 
        { 
            var project = await _projectsService.GetProject(id);
            if (project.IsSuccess)
            {
                var projectRequest = new UpdateProjectRequest(id, project.Value.Title, project.Value.Description);
                return View(projectRequest);
            }

            return RedirectToAction("GetAll");
        }

        [HttpPost]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public async Task<IActionResult> EditProject(UpdateProjectRequest projectRequest)
        {
            var project = ProjectModel.Create(
                projectRequest.Id,
                projectRequest.Title,
                projectRequest.Description,
                new List<SprintModel>());

            if (project.IsFailure)
            {
                return View(projectRequest);
            }

            var projectUpdate = await _projectsService.UpdateProject(project.Value);

            if (projectUpdate.IsSuccess) 
            {
                return RedirectToAction("GetAll", projectRequest.Id);
            }

            return View(project);
        }

    }
}

TaskBoard.AP/Controllers/TasksController.cs
using Microsoft.AspNetCore.Mvc;
using TaskBoard.Domain.Interfaces.Services;
using TaskBoard.Domain.Models;
using TaskBoard.Domain.Enum;
using TaskBoard.Domain.Extensions;
using TaskBoard.API.Contracts.Task;
using Microsoft.AspNetCore.Authorization;

namespace TaskBoard.API.Controllers
{
    public class TasksController : Controller
    {
        private readonly ITasksService _tasksService;
        public TasksController(ITasksService tasksService)
        {
            _tasksService = tasksService;
        }

        [HttpGet]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public IActionResult CreateTask(Guid idSprint)
        {
            var taskRequest = new CreateTaskRequest(
                idSprint, 
                string.Empty, 
                string.Empty, 
                StatusTask.Expectation, 
                string.Empty);

            return View(taskRequest);
        }

        [HttpPost]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public async Task<IActionResult> CreateSprint(CreateTaskRequest taskRequest)
        {
            var task = TaskModel.Create(
                taskRequest.SprintId,
                Guid.Empty,
                taskRequest.Title,
                taskRequest.Description,
                taskRequest.Comment);

            if (task.IsFailure)
            {
                return View(taskRequest);
            }

            await _tasksService.CreateTask(task.Value);

            return RedirectToAction("GetSprint", "Sprints", new { id = taskRequest.SprintId });
        }

        [HttpGet]
        [Authorize(Policy = "AllNotBanedUsers")]
        public async Task<IActionResult> GetTask(Guid id)
        {
            var task = await _tasksService.GetTask(id);

            if (task.IsSuccess)
            {
                return View(task.Value);
            }

            return View(task.Error);
        }

        [HttpGet]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public async Task<IActionResult> DeleteTask(Guid id)
        {
            var task = await _tasksService.GetTask(id);

            await _tasksService.DeleteTask(id);

            return RedirectToAction("GetSprint", "Sprints", new { id = task.Value.SprintId });
        }

        [HttpGet]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public async Task<IActionResult> EditTask(Guid id)
        {
            var task = await _tasksService.GetTask(id);
            
            if (task.IsSuccess)
            {
                var taksRequest = new UpdateTaskRequest(
                    id,
                    task.Value.SprintId,
                    task.Value.Title,
                    task.Value.Description,
                    task.Value.Status,
                    task.Value.Comment);

                return View(taksRequest);
            }

            return BadRequest("Задача не была найдена");
        }

        [HttpPost]
        [Authorize(Policy = "AdminOrManagerPolicy")]
        public async Task<IActionResult> EditTask(UpdateTaskRequest taskRequest)
        {
            var task = TaskModel.Create(
               taskRequest.SprintId,
               taskRequest.Id,
               taskRequest.Title,
               taskRequest.Description,
               taskRequest.Comment);

            if (task.IsFailure)
            {
                return View(taskRequest);
            }
            task.Value.UpdateStatus(taskRequest.Status);

            var taskUpdate = await _tasksService.UpdateTask(task.Value);

            if (taskUpdate.IsSuccess)
            {
                return RedirectToAction("GetTask", new { id = taskRequest.Id });
            }

            return View(taskRequest);
        }
        
        [HttpGet]
        [Authorize(Policy = "AllNotBanedUsers")]
        public async Task<IActionResult> StartTask(Guid id)
        {
            var task = await _tasksService.GetTask(id);

            if (task.IsFailure)
            {
                return BadRequest($"{task.Error}");
            }

            task.Value.UpdateStatus(StatusTask.InProgress);

            await _tasksService.UpdateTask(task.Value);

            return RedirectToAction("GetTask", new { id });
        }

        [HttpGet]
        [Authorize(Policy = "AllNotBanedUsers")]
        public async Task<IActionResult> PostponeTask(Guid id)
        {
            var task = await _tasksService.GetTask(id);

            if (task.IsFailure)
            {
                return BadRequest($"{task.Error}");
            }

            task.Value.UpdateStatus(StatusTask.Expectation);

            await _tasksService.UpdateTask(task.Value);

            return RedirectToAction("GetTask", new { id });
        }

        [HttpGet]
        [Authorize(Policy = "AllNotBanedUsers")]
        public async Task<IActionResult> CompleteTask(Guid id)
        {
            var task = await _tasksService.GetTask(id);

            if (task.IsFailure)
            {
                return BadRequest($"{task.Error}");
            }

            task.Value.UpdateStatus(StatusTask.Сompleted);

            await _tasksService.UpdateTask(task.Value);

            return RedirectToAction("GetTask", new { id });
        }
    }
}

TaskBoard.AP/Views/Tasks/CreateTask.cshtml
@using TaskBoard.API.Contracts
@using TaskBoard.Domain.Models;
@using TaskBoard.API.Contracts.Task;
@model CreateTaskRequest

<h2>Создание задачи</h2>
<form asp-action="CreateSprint" method="post">
    <input type="hidden" name="SprintId" value="@Model.SprintId">
    <input type="hidden" name="Status" value="@Model.Status">
    <div class="form-group"> 
        <label for="Title">Название:</label>
        <input type="text" class="form-control" id="Title" name="Title" required>
    </div>
    <div class="form-group">
        <label for="Description">Описание:</label>
        <textarea class="form-control" id="Description" name="Description" required></textarea>
    </div>
    <div class="form-group">
        <label for="Comment">Комментарий:</label>
        <textarea class="form-control" id="Comment" name="Comment" required></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Создать</button>
    <a href="@Url.Action("GetSprint", "Sprints", new { id = @Model.SprintId })" class="btn btn-secondary">Назад к проекту</a>
</form>

TaskBoard.AP/Views/Tasks/EditTask.cshtml
@using TaskBoard.API.Contracts;
@using TaskBoard.API.Contracts.Task;
@model UpdateTaskRequest

<h2>Редактирование Задачи</h2>

<form asp-action="EditTask" method="post">
    <div class="form-group">
        <input type="hidden" name="Id" value="@Model.Id">
        <input type="hidden" name="ProjectId" value="@Model.SprintId">
        <input type="hidden" name="Status" value="@Model.Status">
        <label for="Title">Название:</label>
        <input type="text" class="form-control" id="Title" name="Title" value="@Model.Title" required>
    </div>
    <div class="form-group">
        <label for="Description">Описание:</label>
        <textarea class="form-control" id="Description" name="Description" required>@Model.Description</textarea>
    </div>
    <div class="form-group">
        <label for="Comment">Комментарий:</label>
        <textarea class="form-control" id="Comment" name="Comment">@Model.Comment</textarea>
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="@Url.Action("GetProject","Projects", new { id = Model.SprintId })" class="btn btn-secondary">Вернуться</a>
</form>

TaskBoard.AP/Views/Tasks/GetTask.cshtml
@using TaskBoard.Domain.Models;
@using TaskBoard.Domain.Enum;
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@model TaskModel

<div>
    <a href="@Url.Action("GetSprint", "Sprints", new { id = Model.SprintId })" class="btn btn-primary">Вернуться к спринту</a>
    <h2>@Model.Title</h2>
    <h2>Описание:</h2>
    <p>@Model.Description</p>
     @if (!string.IsNullOrEmpty(Model.Comment))
     {
        <h3>Комментарий:</h3>
        <p>@Model.Comment</p>
     }
</div>
@if (AuthorizationService.AuthorizeAsync(User, null, "AdminOrManagerPolicy").Result.Succeeded)
{
    <a href="@Url.Action("EditTask", new { id = Model.Id })" class="btn btn-primary">Редактировать задачу</a>
    <a href="@Url.Action("DeleteTask", new { id = Model.Id })" class="btn btn-danger">Удалить задачу</a>
}
@{
    var status = Model.Status;
    var userId = Guid.Parse(User.Claims.FirstOrDefault(c => c.Type == "userId").Value);
}

@if (AuthorizationService.AuthorizeAsync(User, null, "AdminPolicy").Result.Succeeded ||
          Model.Sprint.UserId == userId)
{
    @if (status == StatusTask.Expectation)
    {
        <a href="@Url.Action("StartTask", "Tasks", new { id = Model.Id })" class="btn btn-success">Приступить к выполнению задачи</a>
    }
    else if (status == StatusTask.InProgress)
    {
        <a href="@Url.Action("PostponeTask", "Tasks", new { id = Model.Id })" class="btn btn-warning">Отложить задачу</a>
        <a href="@Url.Action("CompleteTask", "Tasks", new { id = Model.Id })" class="btn btn-primary">Завершить выполнение задачи</a>
    }   
    else if (status == StatusTask.Сompleted)
    {
        <a href="@Url.Action("StartTask", "Tasks", new { id = Model.Id })" class="btn btn-success">Вернуться к задачи</a>
    }
}

<h3>Файлы</h3>
@if (Model.Files.Any())
{
    <ul>
        @foreach (var file in Model.Files)
        {
            <li>
                @if (!string.IsNullOrEmpty(file.FileName))
                {
                    var fileName = System.IO.Path.GetFileName(file.FileName);
                    <a href="@Url.Action("DownloadFile", "Files", new { id = file.Id })">@fileName</a>
                }
                <form asp-action="DeleteFile" asp-controller="Files" method="post">
                    <input type="hidden" name="id" value="@file.Id" />
                    <button type="submit" class="btn btn-danger">Удалить файл</button>
                </form>
            </li>
        }
    </ul>
}
else
{
    <p>В задаче пока нет файлов.</p>
}

<form asp-action="UploadFileToTask" asp-controller="Files" method="post" enctype="multipart/form-data">
    <input type="hidden" name="sprintId" value="@Model.Id" />
    <div class="form-group">
        <label for="file">Выберите файл для загрузки: </label>
        <input type="file" class="form-control-file" id="file" name="file" required>
    </div>
    <button type="submit" class="btn btn-primary">Добавить файл</button>
</form>